### PR TITLE
Fixed color in mcmeta description

### PR DESCRIPTION
**Pull request by HeDeAnTheonlyone**
I changed it from `orange` to `#FF631A` (Datapack Hub orange)

### CODE REVIEW

**Review by FIyrr — APPROVED** [review]

**Comment by Sleet827** [comment]
colour*

(I was granted permission to send this by @Silabear)

**Comment by HeDeAnTheonlyone** [comment]
@Sleet827 
don't care, didn't ask

**Comment by Silabear** [comment]
> @Sleet827
> don't care, didn't ask

He is correct tho

**Review by Silabear — APPROVED** [review]
I approve these changes

**Pull request merged**
